name: meloplay
description: "Meloplay is a local music player app that plays music from your device."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.3.8

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^9.0.0 # state management
  flutter:
    sdk: flutter # flutter sdk
  flutter_bloc: ^9.1.0 # state management
  flutter_cache_manager: ^3.4.1
  flutter_staggered_animations: ^1.1.1 # animation
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  get_it: ^8.0.3 # dependency injection
  hive: ^2.2.3 # local database
  hive_flutter: ^1.1.0 # local database
  just_audio: ^0.9.46 # audio player
  just_audio_background: ^0.0.1-beta.15 # audio player background
  lottie: ^3.3.1
  marquee: ^2.3.0
  on_audio_query: ^2.9.0 # get songs from device
  package_info_plus: ^8.3.0 # get app info
  permission_handler: ^11.4.0 # get permission
  rxdart: ^0.28.0 # stream
  share_plus: ^10.1.4 # share song
  url_launcher: ^6.3.1 # open url

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # linter
  flutter_launcher_icons: ^0.14.3 # app icon generator

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/lottie/
    - assets/images/
    - assets/svg/
